# Generated by Django 5.2.14 on 2026-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
